services:

  postgres:
    image: postgres:17
    container_name: ghostcheck-postgres

    environment:
      POSTGRES_DB: ghostcheck
      POSTGRES_USER: ghostcheck
      POSTGRES_PASSWORD: ghostcheck

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ghostcheck -d ghostcheck"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:8-alpine
    container_name: ghostcheck-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data


  api-gateway:
    build:
      context: ./services/api-gateway

    container_name: ghostcheck-api-gateway

    environment:
      DATABASE_URL: postgresql+psycopg2://ghostcheck:ghostcheck@postgres:5432/ghostcheck
      REDIS_URL: redis://redis:6379

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started


  collector-service:
    build:
      context: ./services/collector-service

    container_name: ghostcheck-collector

    environment:
      API_GATEWAY_URL: http://api-gateway:8000
      REDIS_URL: redis://redis:6379

    ports:
      - "8001:8001"

    depends_on:
      - api-gateway
      - redis


  collector-worker:
    build:
      context: ./services/collector-service

    container_name: ghostcheck-collector-worker

    environment:
      API_GATEWAY_URL: http://api-gateway:8000
      REDIS_URL: redis://redis:6379

      # Bright Data
      BRIGHT_DATA_API_KEY: ${BRIGHT_DATA_API_KEY}
      BRIGHT_DATA_URL: ${BRIGHT_DATA_URL}

      # Source-specific datasets
      LINKEDIN_JOBS_DATASET_ID: ${LINKEDIN_JOBS_DATASET_ID}
      INDEED_JOBS_DATASET_ID: ${INDEED_JOBS_DATASET_ID}
      GLASSDOOR_JOBS_DATASET_ID: ${GLASSDOOR_JOBS_DATASET_ID}

    command:
      [
        "uv",
        "run",
        "python",
        "-u",
        "-m",
        "app.worker"
      ]

    depends_on:
      - redis
      - api-gateway


  detection-service:
    build:
      context: ./services/detection-service

    container_name: ghostcheck-detection

    environment:
      DATABASE_URL: postgresql+psycopg2://ghostcheck:ghostcheck@postgres:5432/ghostcheck
      REDIS_URL: redis://redis:6379

    ports:
      - "8002:8002"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started


  detection-worker:
    build:
      context: ./services/detection-service

    container_name: ghostcheck-detection-worker

    environment:
      DATABASE_URL: postgresql+psycopg2://ghostcheck:ghostcheck@postgres:5432/ghostcheck
      REDIS_URL: redis://redis:6379

    command:
      [
        "python",
        "-u",
        "-m",
        "app.worker"
      ]

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started


volumes:
  postgres_data:
  redis_data: