"""add unique job source identity

Revision ID: 86583a603e1e
Revises: bc2b50f7e41d
Create Date: 2026-08-29 00:07:56.497504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86583a603e1e'
down_revision: Union[str, Sequence[str], None] = 'bc2b50f7e41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_job_source_external_id', 'jobs', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_source_external_id', 'jobs', type_='unique')
    # ### end Alembic commands ###
