"""add job source identity

Revision ID: bc2b50f7e41d
Revises: bb1029b15a83
Create Date: 2026-08-28 21:44:38.231900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2b50f7e41d'
down_revision: Union[str, Sequence[str], None] = 'bb1029b15a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'source')
    op.drop_column('jobs', 'external_id')
    # ### end Alembic commands ###
